#cs
--- Tag 9: Hängebrücke ---
Diese Hängebrücke knarrt, wenn man sie entlanggeht. Sie sind sich nicht sicher, wie alt es ist oder ob es überhaupt Ihr Gewicht tragen kann.

Es scheint die Elfen jedoch gut zu unterstützen. Die Brücke überspannt eine Schlucht, die der gewaltige Fluss tief unter Ihnen geformt hat.

Sie treten vorsichtig; Dabei dehnen und verdrehen sich die Seile. Sie beschließen, sich abzulenken, indem Sie Seilphysik modellieren; Vielleicht kannst du sogar herausfinden, wohin du nicht treten solltest.

Betrachten Sie ein Seil mit einem Knoten an jedem Ende; Diese Knoten markieren den Kopf und das Ende des Seils. Bewegt sich der Kopf weit genug vom Schwanz weg, wird der Schwanz zum Kopf gezogen.

Aufgrund der nebulösen Argumentation mit Planck-Längen sollten Sie in der Lage sein, die Positionen der Knoten auf einem zweidimensionalen Gitter zu modellieren. Dann können Sie bestimmen, wie sich der Schwanz bewegen wird, indem Sie einer hypothetischen Reihe von Bewegungen (Ihrer Rätseleingabe) für den Kopf folgen.

Aufgrund der oben genannten Planck-Längen muss das Seil ziemlich kurz sein; Tatsächlich müssen sich Kopf (H) und Schwanz (T) immer berühren (diagonal benachbart und sogar überlappend zählen beide als berührend):

....
.TH.
....

....
.H..
..T.
....

...
.H. (H überdeckt T)
...
Wenn der Kopf jemals zwei Schritte direkt vom Schwanz nach oben, unten, links oder rechts entfernt ist, muss sich der Schwanz auch einen Schritt in diese Richtung bewegen, damit er nahe genug bleibt:

..... ..... .....
.TH.. -> .T.H. -> ..TH.
..... ..... .....

... ... ...
.T. .T. ...
.H. -> ... -> .T.
...    .H. .H.
... ... ...
Andernfalls, wenn Kopf und Schwanz sich nicht berühren und sich nicht in derselben Zeile oder Spalte befinden, bewegt sich der Schwanz immer einen Schritt diagonal, um mitzuhalten:

..... ..... .....
..... ..H.. ..H..
..H.. -> ..... -> ..T..
.T... .T... .....
..... ..... .....

..... ..... .....
..... ..... .....
..H.. -> ...H. -> ..TH.
.T... .T... .....
..... ..... .....
Sie müssen nur herausfinden, wohin der Schwanz geht, während der Kopf einer Reihe von Bewegungen folgt. Angenommen, der Kopf und der Schwanz beginnen beide an derselben Position und überlappen sich.

Zum Beispiel:

R4
U 4
L 3
D 1
R4
D 1
L5
R2
Diese Abfolge von Bewegungen bewegt den Kopf vier Schritte nach rechts, dann vier Schritte nach oben, dann drei Schritte nach links, dann einen Schritt nach unten und so weiter. Nach jedem Schritt müssen Sie die Position des Schwanzes aktualisieren, wenn der Schritt bedeutet, dass der Kopf nicht mehr an den Schwanz angrenzt. Optisch laufen diese Bewegungen wie folgt ab (s markiert die Ausgangsposition als Bezugspunkt):

== Ausgangszustand ==

......
......
......
......
H..... (H deckt T, s)

== R4 ==

......
......
......
......
TH.... (T deckt s ab)

......
......
......
......
etw...

......
......
......
......
s.TH..

......
......
......
......
s..th.

== U 4 ==

......
......
......
....H.
s..T..

......
......
....H.
....T.
s.....

......
....H.
....T.
......
s.....

....H.
....T.
......
......
s.....

== L3 ==

...H..
....T.
......
......
s.....

..HT..
......
......
......
s.....

.HT...
......
......
......
s.....

== D1 ==

..T...
.H....
......
......
s.....

== R4 ==

..T...
..H...
......
......
s.....

..T...
...H..
......
......
s.....

......
...TH.
......
......
s.....

......
....TH
......
......
s.....

== D1 ==

......
....T.
.....H
......
s.....

== L5 ==

......
....T.
....H.
......
s.....

......
....T.
...H..
......
s.....

......
......
..HT..
......
s.....

......
......
.HT...
......
s.....

......
......
HT....
......
s.....

== R2 ==

......
......
.H.... (H überdeckt T)
......
s.....

......
......
.TH...
......
s.....
Nachdem Sie das Seil simuliert haben, können Sie alle Positionen zählen, die der Schwanz mindestens einmal besucht hat. In diesem Diagramm markiert s wieder die Startposition (die der Schwanz auch besucht hat) und # markiert andere Positionen, die der Schwanz besucht hat:

..##..
...##.
.####.
....#.
s###..
Es gibt also 13 Positionen, die der Schwanz mindestens einmal besucht hat.

Simulieren Sie Ihre komplette hypothetische Bewegungsserie. Wie viele Positionen besucht das Ende des Seils mindestens einmal?
#ce


#include <File.au3>
#include <Array.au3>
Global $Input
Global $result=-1
;~ _FileReadToArray("2022_Day-8.txt",$Input,1)
_FileReadToArray("2022_Day-9_B.txt",$Input,1)
;~ _ArrayDisplay($Input)
Global $Matrix[8][8]
Global $Tail[2]=[4,0]
Global $Head[2]=[4,0]
_ArrayDisplay($Head)
For $i=0 to 7
	For $j=0 To 7
		$Matrix[$i][$j]="."
	Next
Next
$Matrix[4][0]="s"

_ArrayDisplay($Matrix)

For $i=1 To $Input[0]
	Local $Split=StringSplit($Input[$i]," ")
	_ArrayDisplay($Split)
	Switch $Split[1]
		Case "R"
			$Head[1]=$Head[1]+Number($Split[2])

		Case "L"
			$Head[1]=$Head[1]-Number($Split[2])
		Case "U"
			$Head[0]=$Head[0]-Number($Split[2])
		Case "D"
			$Head[0]=$Head[0]+Number($Split[2])
	EndSwitch
$Matrix[$Head[0]][$Head[1]]="H"
_ArrayDisplay($Matrix)
Next
Exit

MsgBox(0,"Day-9_StarOne",$result) ; falsch 491 (low)
ClipPut($result)
